### ISSUE TITLE
[Feature request] Handle output as binary on hash_hmac function

### ISSUE THREAD

**Issue by CaporalDead** [octohk/feedback#9]
Hi again !

Could it be possible to customize the last parameter of the hash_hmac function ? It's a boolean that indicates if the output should be "as binary". This argument is part of the implementation of the hmac function.

Let me know if you need any feedback on the usecase :).

Again, thanks for your work

**Comment by lorisleiva** [comment]
Hi Thomas 👋 

Thanks for the feedback.

We've actually got this for the "Create JWT" node but for some reason we didn't add it to the "Hash text" node. Is this what you are looking for?

If so, I'll make sure to work on this today (with #8).

<img width="831" alt="Capture 2021-03-02T10 04 51@2x" src="https://user-images.githubusercontent.com/3642397/109632309-cd733380-7b3e-11eb-84a6-48fcc0062ff5.png">

**Comment by CaporalDead** [comment]
Just to be sure that we're on the same page :), I'm talking about [this parameter](https://www.php.net/manual/en/function.hash-hmac.php) on the hash_hmac function.

**Comment by lorisleiva** [comment]
Hey Thomas, 👋 

I tried implementing this today but I've had some fundamental issues.

Creating a binary hash works fine and it get properly passed from one node to the other. However, when displaying the data or if we need to persist the output of this node, then we have issues since binary data doesn't play well with JSON.

I tried looking for a stable binary check so I can recognise when a string is a binary and then parse it into something that will work to both display it and persist it but there is no way of achieving this with 100% reliability (it's all regexes that _should_ work most of the time).

The ideal thing to do would be to wrap this value in a special class that get treated differently based on where it goes.

I would definitely like to explore that path since it will allow binary data to flow through the workflow and will free some other nodes from binary inputs (like the Create JWT node).

I'll be sure to keep you posted whenever something changes in that regard.

In the meantime, could you tell me more about why you need to output a binary hash so I can see if we can find a workaround for you?

**Comment by CaporalDead** [comment]
Thanks for the feedback @lorisleiva,

My usecase is pretty simple, the service that is bound as an input, generate a signature using this exact method :

`base64_encode(hash_hmac('sha256', $rawPayload . $timestamp, $secret, true))`

To validate that the input payload is valid, I need to reproduce those 2 operations : 
* base64_encode
* hash_hmac (fourth parameter) as binary output

I did not found a work around for now but I found have something in mind let me know :)

**Comment by CaporalDead** [comment]
By the way, are you sure that you want to display an output as binary ? Is it really relevant to display as it is ?

I'm just challenging your thoughts, I'm not telling you what to do with your product :D

**Comment by lorisleiva** [comment]
Ah no, it's not just about displaying. Even if I decided not to display the value during evaluation preview or not to persist binary data, I'd still need to find a way to know if that variable is binary data in the first place. Which is the source of the issue here.

For you use-case, I could make it return a base64 encode of the binary hmac directly but this seems too specific for a node input.

Can I ask which service it is that you're integrating with? There might be as consideration to add them as a officially supported platform so you can just use the `Platform verifier` node.

**Comment by CaporalDead** [comment]
Yes sure you can, the service I'm trying to integrate is "Digitaleo", the company I work for :).

Our webhooks doc is [available here](https://documenter.getpostman.com/view/6740351/S17oxppy)

**Comment by CaporalDead** [comment]
Let me know if you want to discuss about that @lorisleiva

**Comment by lorisleiva** [comment]
Hey, sorry for the late reply. I’d love for us to integrate your company at some point but since we’ve got so few at the moment we’d rather focus on integrations that can reach the most users.

I’ll keep this issue open until we properly support binary data flowing in the workflows.

I’ll also let you know if I find a workaround in the meantime. 🙂

**Comment by CaporalDead** [comment]
Hi @lorisleiva,

Do you have any update about this subject :) ?

**Comment by lorisleiva** [comment]
Hi Thomas, even though this is a priority for the Octohook roadmap, I’ve got quite a lot of backlog that accumulated on my open source stuff lately so I’m not sure when exactly I’ll have the chance to take care of it but don’t worry it’s not forgotten. 🙂

**Comment by CaporalDead** [comment]
All right @lorisleiva thanks !

**Comment by lorisleiva** [comment]
Hi Thomas 👋 

I do apologise for the delay. This little feature required quite a lot of refactoring (that had to be done anyway) so that values being passed between nodes have additional context. In this case, whether the provided text is a binary representation or not.

In any case, this is now available and deployed!

As you can see in the images below, even though the "Hash" and "Binary hash" display the same text (since we decided to display binary texts as hexadecimals), their internal representation is different and, therefore, their base64 encoding will be different as well.

### Encoded hash

<img width="1003" alt="Capture 2021-07-06T11 42 55@2x" src="https://user-images.githubusercontent.com/3642397/124587964-26860780-de50-11eb-9c7a-a887c8c09865.png">

### Encoded binary hash

<img width="988" alt="Capture 2021-07-06T11 42 32@2x" src="https://user-images.githubusercontent.com/3642397/124587990-2d147f00-de50-11eb-8c51-3f4e4244d826.png">

(Also note the new workflow design which I hope should be more user friendly than the previous one)

I hope this will help you build your workflows and please let me know if there's anything else you need. I promise it won't always take that long! 😅
